### ISSUE TITLE
Create Article: Logical Order in If Else Statements

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/wiki#1009]
The [Logical Order in If Else Statements challenge](https://www.freecodecamp.com/challenges/logical-order-in-if-else-statements) has no Wiki article and should have one.

&nbsp;
<br>
<br>

> ----
<p align="center">Need Help? Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>or Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Currently Assigned to:** @varunu28 

> *If you want to work on this, please comment below or we can chat over* <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>gitter</b></a></kbd>
Note: you may be assigned **only if** the current assignee doesn't respond within the given time-frame of 7 days.

**Comment by varunu28** [comment]
Hi @erictleung  I would like to work on this. I will come up with an article in next 1 day. Please assign this to me.

**Comment by erictleung** [comment]
@varunu28 go for it! You don't need to be assigned to work on it. Just pick it up and make a PR when you've finished it. Just an fyi, I don't have write access to the Wiki so you'll need someone else merge your PR when you're done :smile: Good luck!

**Comment by varunu28** [comment]
@erictleung Ok. Just to be sure. We need to create a wiki article explaining the flow of if-else statements ie IF-ELSEIF-ELSE
Correct?

**Comment by erictleung** [comment]
@varunu28 yes, I would checkout [the challenge itself](https://www.freecodecamp.com/challenges/logical-order-in-if-else-statements) and maybe explain the example they give.

I would also take a look at the Wiki articles around it to get a sense of what and how much to add.

- https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Challenge-Comparisons-With-The-Logical-And-Operator
- https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Challenge-Chaining-If-Else-Statements
- https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Challenge-Introducing-Else-If-Statements
- https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Challenge-Introducing-Else-Statements

You can also visit the [Wiki Gitter Help Room](https://gitter.im/FreeCodeCamp/Wiki) for any questions you have.

**Comment by varunu28** [comment]
Thanks @erictleung . I would start working on it and make a PR by tomorrow.

**Comment by abhisekp** [comment]
@varunu28 Thank you for your interest :tada: 

You've been assigned. See https://github.com/FreeCodeCamp/wiki/issues/1009#issue-156135000 (*issue message*)
