### ISSUE TITLE
3 Broken Links on Front Page of Wiki

### ISSUE THREAD

**Issue by RyanMarten** [FreeCodeCamp/wiki#1016]
On [this ](https://www.freecodecamp.com/wiki/en/) page clicking on the words "CodeBot" "Template" or "Wiki Central" brings you to a missing github link.

**Comment by Rafase282** [comment]
Thank you, We are aware of that and we are working on a solution.

**Comment by Rafase282** [comment]
The wiki has been moved to the forum now.
