### ISSUE TITLE
Improve `Python-Decorators` article

### ISSUE THREAD

**Issue by meetmangukiya** [FreeCodeCamp/wiki#1022]
Just providing the links isn't that useful. Campers would get those links from Google too. Enclosing it just in an article doesn't seem to be that of a help! I got no knowledge about `decorators` otherwise I'd have raised a PR already.

**Comment by meetmangukiya** [comment]
Actually I was looking for the wiki article to understand the `decorators` part. :sweat_smile:

**Comment by erictleung** [comment]
Easy access to [article-in-need](https://github.com/FreeCodeCamp/wiki/blob/master/Python-Functions-Decorators.md) for anyone wanting to fix this. I've always heard of these things too but never quite understood them too.

**Comment by meetmangukiya** [comment]
@erictleung Which things you talking about 
> I've always heard of these things too but never quite understood them too.?
Decorators?  :confused:

**Comment by erictleung** [comment]
Haha sorry, yeah I was referring to decorators :)

**Comment by meetmangukiya** [comment]
Ohh. cool :+1:

**Comment by erictleung** [comment]
@atjonathan this issue looks resolved with #1037, unless it still needs work.

**Comment by atjonathan** [comment]
Thanks @erictleung :sparkles:, yeh this has been resolved.
