### ISSUE TITLE
Fix link on Home.md

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/wiki#1050]
On [Home.md](https://github.com/FreeCodeCamp/wiki/blob/master/Home.md) the link to **Wiki Central** needs changed.
Because we recently switched all our links to lowercase, **Wiki Central** is linking to http://freecodecamp.github.io/wiki/en/Wiki-Central/ instead of http://freecodecamp.github.io/wiki/en/wiki-central/.
Is the wiki generator not fixing the lowercase issue for Home.md?
Tagging @Rafase282

**Comment by Rafase282** [comment]
The Links remain the same, the generator is the one that makes it lowercase for use.

**Comment by atjonathan** [comment]
@Rafase282 Looks like the generator isn't running for `Home.md`?

**Comment by atjonathan** [comment]
@Rafase282 Looks like the generator isn't running for `Home.md`?

**Comment by Rafase282** [comment]
Check on the live version, if I remember correctly I got it running last
time I made changes. I'll take a look when I get back.

On Fri, May 27, 2016, 2:02 PM Jonathan <notifications@github.com> wrote:

> @Rafase282 <https://github.com/Rafase282> Looks like the generator isn't
> running for Home.md?
>
> —
>
>
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/FreeCodeCamp/wiki/issues/1050#issuecomment-222214102>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AARZ0pLDkz3SlKKxTy2QM0UJmv-QijaBks5qFzGpgaJpZM4Iop6o>
> .
>
-- 
Kind Regards,

Rafael Rodríguez
Junior Web Developer
https://rafase282.github.io/

**Comment by atjonathan** [comment]
@Rafase282, this appears to still be an issue.

**Comment by Rafase282** [comment]
This and all similar related issues as tied to the race condition on the wiki generator.
I do not want to just change the links to hard links on that page. If we were to do that, we should do it for all links,a nd use html while we are at it. Which is why we need to work on https://github.com/FreeCodeCamp/wiki-generator/issues/58

**Comment by Rafase282** [comment]
I'm closing due to the migration.
