### ISSUE TITLE
Heroku problem

### ISSUE THREAD

**Issue by Ierofantis** [FreeCodeCamp/wiki#1058]
There is a problem for anybody who hasn't got a credid card because he can't deploy more than five projects.

**Comment by alayek** [comment]
Yes, unfortunately 5 is the heroku limit _per account_ for free hosting. You might want to take this up with [Heroku people.](https://www.heroku.com/contact).

**Comment by Ierofantis** [comment]
Maybe It would be a good idea for anyone he wants to use some alternatives like : https://alternativeto.net/software/heroku/

**Comment by atjonathan** [comment]
Refer FreeCodeCamp/FreeCodeCamp#8773
