### ISSUE TITLE
Create Article: Hikes Contributing Guide

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/wiki#1067]
This should include details on:
- Scripting
- Recording
- Editing
- Uploading

Probably more, i'm still not certain on the current workflow of hikes :stuck_out_tongue_closed_eyes: 

cc/ @FreeCodeCamp/hikes @Septimus @brianamarie

**Comment by brianamarie** [comment]
Starting point - 

## Hike Contributing Workflow

#### Preparation 
- [ ] Check out these resources to get ready
  - [ ] [Article with general guidelines](https://medium.freecodecamp.com/let-s-go-for-a-hike-here-s-your-map-4301df6e3801#.f91m4eq85)
  - [ ] [Video challenge chat](https://gitter.im/FreeCodeCamp/hikes)
  - [ ] [Hike repository](https://github.com/FreeCodeCamp/hikes)
- [ ] Pick a topic based on the existing issues in the hike repository

### Getting Started with a Pull Request
- [ ] Propose a script as a [markdown file](https://guides.github.com/features/mastering-markdown/) in a Pull Request
  - Create a new branch with `<yourusername-videoname>`
  - Create a new file labeled `<video-title.md>` within the appropriate folder (`scripts/<unit-title>/<video-title.md>`). If that folder doesn't exist yet, create one!
  - Save your changes and open a pull request comparing to master. `@` mention brianamarie for feedback.

### Recording
- [ ] Record your video
  - Set up a whiteboard and record your video 
- [ ] Comment in your PR with the link to your video. `@` QuincyLarson and brianamarie
  - You'll get feedback, and we'll work with you to help refine the video so we can include it on FreeCodeCamp.com

### Finishing touches
- [ ] Open a PR in the [Free Code Camp repository](https://github.com/freecodecamp/freecodecamp) including your video links, scripts, thumbnail images, and questions to get them added to the site.

**Comment by brianamarie** [comment]
I would love to fill out the above example with more specific guidelines, especially on items not currently documented like [how to add videos to JSON and adding overlays to thumbnails](https://github.com/FreeCodeCamp/hikes/issues/185).
