### ISSUE TITLE
Fix link in Gitter-Moderation-Policy.md

### ISSUE THREAD

**Issue by sludge256** [FreeCodeCamp/wiki#1083]
The current link in the boilerplate message (step 2) points to:
http://www.freecodecamp.com/FreeCodeCamp-Code-Of-Conduct

but the actual page is at:
https://www.freecodecamp.com/code-of-conduct

**Comment by tianz** [comment]
Hey I would like to work on this one. I have made two pull requests to FreeCodeCamp but this is my first time working on the wiki. I am wondering if I should follow the same steps? (e.g. create a branch, commit to my own repo, and then send a pull request?
