### ISSUE TITLE
JS Functions page is missing content

### ISSUE THREAD

**Issue by glgirl28** [FreeCodeCamp/wiki#1096]
There is no content on this wiki page: https://github.com/freecodecamp/freecodecamp/wiki/JS-Functions

There is only the word "Stub" on the page:

**Comment by Rafase282** [comment]
Yes I'm aware of that, we haven't got around it yet, but given the massive
issue about is functions we are planing to add, I'm sure that will be
updated. However, if you would like to add content to it, feel free to send
a pull request, thanks.

On Tue, Jun 7, 2016, 4:28 PM glgirl28 <notifications@github.com> wrote:

> There is no content on this wiki page:
> https://github.com/freecodecamp/freecodecamp/wiki/JS-Functions
>
> There is only the word "Stub" on the page:
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FreeCodeCamp/wiki/issues/1096>, or mute the thread
> <https://github.com/notifications/unsubscribe/AARZ0g1-iEVCn5ov6Twjcg85NGHD6LTAks5qJdSFgaJpZM4IwU8W>
> .
>
-- 
Kind Regards,

Rafael Rodríguez
Junior Web Developer
https://rafase282.github.io/

**Comment by CruiseDevice** [comment]
Does this page intended to have information about JavaScript Functions.

**Comment by Rafase282** [comment]
It was supposed to, that is old. We do have the JavaScript page where most functions are listed but feel free to populate content for this one.

**Comment by Rafase282** [comment]
The page was not moved to the wiki at the forum, feel free to create a new one.
