### ISSUE TITLE
Improve Translations Guide

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/wiki#1201]
This refers to the older issue #565 

New points to be addressed that were apparently missed while closing the older issue

- Add GIF for PR Creation
- Add Guidelines on Clear naming for PR Creation

Currently this is bit unclear in [this file](https://github.com/FreeCodeCamp/wiki/blob/master/Translation-Create-PR.md) and should be made more precise [like creating issues](https://github.com/FreeCodeCamp/wiki/blob/master/Translation-Create-Issues.md).

**Comment by Rafase282** [comment]
This should be moved to https://github.com/FreeCodeCamp/TranslationExpansion
