### ISSUE TITLE
Chunky Monkey needs better solutions

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/wiki#1205]
Referring https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9500
> The basic solution is very convoluted and intermediate isn't much better. Advanced is OK.
>
> Challenge also might benefit from mentioning the <code>splice</code> method since that is a much simpler approach than <code>slice</code>.
>
> Propose eliminating that ugly basic solution, demoting intermediate to basic, and advanced to intermediate. Also recommend adding <code>splice</code> to list of suggested methods.

**Comment by dakshshah96** [comment]
Working on it. Will open a PR soon. 👍

**Comment by Rafase282** [comment]
The solution has been updated [here](http://forum.freecodecamp.com/t/algorithm-chunky-monkey/16005).
