### ISSUE TITLE
Javascript - Escape Sequences in Strings - \n and \r not interchangeable

### ISSUE THREAD

**Issue by MyNameIsURL** [FreeCodeCamp/wiki#1228]
This is the correct answer to the problem `var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";` but this `var myStr = "FirstLine\r\\SecondLine\\\nThirdLine";` should work as well. It shouldn't matter if the newline is used first or the carriage return is used first as long as both are used according to the instructions. Should be a simple regex fix.

**Comment by Rafase282** [comment]
You are on the wrong repo, it should be the main repo not the wiki one, also the instructions are to encode a specific sequence.
