### ISSUE TITLE
Add JS best practices guide

### ISSUE THREAD

**Issue by N0bl3** [FreeCodeCamp/wiki#1229]
Hello,
don't you think it would be great to introduce a guide to best practices in JS so that even beginners get used to good formatting? This could bgo as far as adding an entry to the wiki and/or proving a linter configuration in the standard FCC generator for projects and/or integrating a tool like JSCS in the FCC text editor.
As an alternative we could regroup some ressources on the subject and put the links in the wiki.

**Comment by Rafase282** [comment]
Best practices could be opinionated but we have some resources available [here](http://forum.freecodecamp.com/t/javascript-tutorials-and-other-resources/14691) that are on the wiki already.

If you want to add more feel free to create or expand on the existing article.
