### ISSUE TITLE
Algorithm Missing Letters conflict

### ISSUE THREAD

**Issue by IsaacAbrahamson** [FreeCodeCamp/wiki#1245]
Algorithm Missing letters Wiki Page
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Algorithm-Missing-Letters

Wiki page states that
> You will create a program that will find the missing letter from a string and add it.

and later

> Hint: 3 You will need to figure out where to insert the letter and how to do it...

However, the actual challenge states:

> Find the missing letter in the passed letter range and return it.

and

> fearNotLetter("abcdefghjklmno") should return "i".

The problem is that the challenge requires you to return the missing letter, but according to the wiki page, you are to add the missing letter to the word and then return the word from what I understood. Somewhat confusing.

**Comment by kaibacorp** [comment]
I found the problem explanation and Hint 3 confusing as well, since there is no insertion or adding of letters occurring. The wording could perhaps be changed to:

> You will create a program that will find and return the missing letter from a string.

and for Hint 3

> You will need to figure out where the missing letter is and how to do it...

Although I'm not certain if the first part of Hint 3 is very helpful.

**Comment by IsaacAbrahamson** [comment]
I edited the wiki post on forums
http://forum.freecodecamp.com/t/algorithm-missing-letters/16023
