### ISSUE TITLE
Merge Conflicts Remnants in Campsite List

### ISSUE THREAD

**Issue by ltegman** [FreeCodeCamp/wiki#190]
In the list of campsites in China there are merge conflict markers. This was originally bugged on the FCC repo in issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5472

**Comment by hallaathrad** [comment]
Master is fine. The issue seems to be in the actual gh_pages, sometime after bundle.js (which also seems to be clean) gets rendered into the page. Ideas, @Rafase282?

**Comment by hallaathrad** [comment]
This is being corrected as per #223

**Comment by ltegman** [comment]
Awesome, thanks!
