### ISSUE TITLE
Need Heroku deployment tutorial

### ISSUE THREAD

**Issue by Rafase282** [FreeCodeCamp/wiki#210]
I as many others had trouble trying to get out first basejump deployed properly on heroku. I know there has been talk about this but to make it official I decided to open an issue asking to this page to be created.

**Comment by Oxyrus** [comment]
@Rafase282 I could create it, however is it really necessary? I mean, with a quick search on Google you can find even a tutorial created by the team at Heroku itself https://devcenter.heroku.com/articles/getting-started-with-nodejs

**Comment by SaintPeter** [comment]
I think there are a few key elements that I would add:
1. Note that if you're doing an express listen server, you should use:
`var port = process.env.PORT || <default port>`
2. Your `package.json` MUST include a `start` script and a typical default would be:  
`"start": "node index.js"`
3. How to create an app with a name of your choosing

I had to do a fair amount of googling to get these because those first two CRITICAL pieces of information are not included in their stupid tutorial.

I think a simple walkthrough on a single page would be quite helpful.

**Comment by Rafase282** [comment]
I had issues before but then with that guided and some poking around I was able to figure out and now I have no issues using it. I do use the github integration instead. I also figured out how to use the environment variables and the mongolab setting. A guide could help campers not having to dig around but after realizing the level of difficulty I'm not particularly inclined fo or against. I do remember it was asked for long ago which is why I still opened the issue.

**Comment by Oxyrus** [comment]
I'll take a look into it later, will comment here when I'm done.

**Comment by eferdman** [comment]
Hey there, just deployed my first basejump to heroku and it was very simple after all. I went through the heroku tutorial for node that @oxyrus posted but I didn't even end up using it. might come in handy later though so who knows. Instead here's what I did:

Heroku Deployment (Easy Way)

1. Create a Heroku account, verify the account. (duh)
2. After making an account, you can go to your dashboard at https://dashboard.heroku.com/apps
3. Click the + sign in the top right hand corner and click Create New App (just like you're making a new repo on github). Give it a name, click Create.
4. After creating the app you'll see it in your dashboard. Click on it. 
5. Then you'll be taken to a dashboard for that app. Click on the Deploy tab.
6. There you'll be happy to see that you can connect to a github repo! YAY! In the Deployment method section, click Github. I think at this point you'll be authenticating heroku with your github account.
7. Right below that, fill in your github repo name. (This of course requires that you've pushed a repo to github from either cloud9 or your local machine. And that you've correctly configured it. More on that below.) 
8. Scroll down again and click Automatic Deploy or scroll down even more and click Manual Deploy. After a few moments you should see your app running at your-repo-name.herokuapp.com. Sweet.

*Creating your app locally. (or on cloud9) The two points @SaintPeter mentioned are really important in making sure the app works on heroku. 

1. Make a new folder called timestamp-microservice or whatever your project is called.
`$ mkdir timestamp-microservice && cd timestamp-microservice`
2. Create the files you're going to need. (There is probably a better way to do this but I'm not sure yet)
`$ touch .env .gitignore README.md index.html server.js`
3. Install packages that you need along the way...
Examples:
`$ npm install --save express`
`$ npm install --save moment`
These will get added to a folder called node_modules in your root folder.
4. Initialize the project with a package.json. Just type: 
`$ npm init`
It'll ask you a series of questions and create a package.json file in your root folder. If you've already created a file called server.js as mentioned above, this essential line gets added to your package.json file:
`"scripts": {
    "start": "node server.js"
  }`
If you name it anything else, though, like 'index.js', that line won't get added and you have to manually add that. That's the default behavior as mentioned [here:]  (https://docs.npmjs.com/files/package.json#default-values)
It'll also add in the node modules you're using without asking, whether you add those before or after creating the package.json.
5. Now create a new repository on github, copy the remote URL, and initialize the project locally by doing:
`$ git init`
`$ git add .`
`$ git commit -m "initial commit"`
`$ git remote add origin <your github url>`
`$ git push -u origin master`

Go back to step 7.

Take a walk. :)

On to my next Basejump!!!

**Comment by SaintPeter** [comment]
I think the above text, with appropriate illustrations, would be an awesome Wiki article.

**Comment by hallaathrad** [comment]
Frivolous as that may be, sometimes I think it'd be fit for github to have a "like" button or equivalent.

**Comment by eferdman** [comment]
thanks, now i just have to figure out how to contribute to the wiki. and how to make new lines in markdown.

**Comment by hallaathrad** [comment]
Fork the wiki, work on your fork, commit and push to it, then from there, make a Pull Request.

**Comment by SaintPeter** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Contribute-To-The-Wiki

**Comment by eferdman** [comment]
ok doing that now. this may take a little while since this will be my first actual contribution and i need to fix the markdown. :)

**Comment by SaintPeter** [comment]
FYI, when you make images, put them into a folder called 
`/images/article-name/imagename.png`
So if your article was "deploying-to-heroku" it would be:
`images/deploying-to-heroku/imagename.png`

**Comment by eferdman** [comment]
thanks @SaintPeter but I haven't done any pics so far. Do you recommend taking screenshots and hosting those online or uploading from the file system? I haven't done too much with that. I'm also weary of copyright infringement so I have really stayed away from using any pix offline. I need to improve in that area. I also keep having issues with Markdown. Darn new lines are not happening. And why is my number 5 turning into a 1? 

Still workin on it. https://github.com/eferdman/wiki/blob/Waypoint-Heroku-Deploy/Waypoint-Heroku-Deployment.md

**Comment by Rafase282** [comment]
@eferdman the link is not working anymore. As for images just take a screenshot, that should be fine as far as I know. It has been done before. If you follow @SaintPeter then you will upload them as part of the commit from your file-system.

As for the numbers changing I have no idea as I don't know what you are doing.

**Comment by SaintPeter** [comment]
@Rafase282 https://github.com/FreeCodeCamp/wiki/blob/master/Heroku-Deployment-Guide.md

It's been live for a while now.

**Comment by Rafase282** [comment]
Then why is this still open? I have to admit I didn't notice when the page was merged.

**Comment by SaintPeter** [comment]
There . . . closed. ;)

**Comment by Rafase282** [comment]
lol I just wanted to know if something else was needed as I saw no update on this for a while but good.
