### ISSUE TITLE
`testingjson` Article has no content

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/wiki#255]
Not sure what is up with this, probably needs to be deleted?
https://github.com/FreeCodeCamp/wiki/blob/master/testingjson.md

**Comment by alistermada** [comment]
Another similarly empty page:
https://github.com/FreeCodeCamp/wiki/blob/master/Test-Me.md

**Comment by Rafase282** [comment]
I think @dcsan and @abhisekp are testing somethign with those pages? Not sure.

**Comment by abhisekp** [comment]
@Rafase282 Those were testing pages for testing how wiki contents show up in chat and how the page shows after trimmed. They're not needed now or can be re-created in personal repo for testing purposes. I think they maybe deleted without any issues.

**Comment by Rafase282** [comment]
I'm handling this.
