### ISSUE TITLE
Update solutions for "Friendly Date Ranges"

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/wiki#296]
The [solution in the wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Bonfire-Friendly-Date-Ranges) doesn't solve the challenge.

This issue addresses FCC's #[6410](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6410) (Already closed).

**Comment by Rafase282** [comment]
Was the challenge updated recently? I tried it again and there are two test that do not pass now.

**Comment by SaintPeter** [comment]
Yes, it was revamped recently.

**Comment by Rafase282** [comment]
Then I guess I'll have to update my code.
