### ISSUE TITLE
Update Translation Page

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/wiki#303]
The current translation page:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/What-to-do-if-you-speak-a-language-that-Free-Code-Camp-does-not-yet-support

points to the Trello board which is no longer used.

Here is a description of the new process:
https://trello.com/c/a5LsOa7B/163-we-are-moving-our-translation-effort-from-trello-to-github-issues-for-each-language-we-need-to-audit-which-challenges-have-not-y

@vtamara - do you want to take this?

**Comment by vtamara** [comment]
Working on it
