### ISSUE TITLE
Lint According to FCC ESlint config

### ISSUE THREAD

**Issue by ltegman** [FreeCodeCamp/wiki#343]
Since changes here get pulled into the camperbot submodule I noticed quite a few linting errors in the scripts.

**Comment by hallaathrad** [comment]
How do we see those so we can clean up?

**Comment by SaintPeter** [comment]
Why do we care if Wiki articles have ESlint errors?

**Comment by hallaathrad** [comment]
because they may cause glitches in bot behaviour, I'm guessing?

**Comment by ltegman** [comment]
@SaintPeter: It's not the articles that have lint errors, it's the JavaScript files in the `scripts/`folder.

There's quite a few approaches you could take, but the simplest would be to copy the .eslintrc from FCC into the scripts folder, add eslint as a dev dependency, and add a script into your `package.json` of "lint": "eslint ./*.js"

**Comment by raisedadead** [comment]
@ltegman @hallaathrad @SaintPeter 

With the formatting of the articles having become so more important now than ever before (referring gatsby issues and the bot hyperlink issues etc) I guess this should be brought in asap.

I am testing out a Sublime plugin called [MarkdownEditing](https://github.com/SublimeText-Markdown/MarkdownEditing) which promises to have a nice [linting feature](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/lint_docs/RULES.md) as well.

I'll update on that, but if works, it would be nice to have something like this.

**Comment by raisedadead** [comment]
Of course this has to be used in conjunction with the JavaScript linting similar to the main repo as being discussed here.

**Comment by Rafase282** [comment]
I'm taking care of this.
