### ISSUE TITLE
Need a JSON or CSV file for List of FCC cities

### ISSUE THREAD

**Issue by samosale** [FreeCodeCamp/wiki#344]
https://github.com/FreeCodeCamp/freecodecamp/wiki/List-of-Free-Code-Camp-city-based-Campsites

If you go to that page you will find the list of all cities. I need that data in csv or json. If you go to google maps you will see that it is using my.csv to generate the chart. It would be perfect if I had that filewith or without coordinates. tnx

**Comment by Rafase282** [comment]
Hello, didn't you already do this? is it okay to close this issue now?
