### ISSUE TITLE
Wiki request - rewrite and simplify explanation of Global Object

### ISSUE THREAD

**Issue by bugron** [FreeCodeCamp/wiki#358]
Original issue: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3416

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object

**Comment by awesomeaniruddh** [comment]
I'd like to take this, but the issue title mentions the 'Global Object' while the MDN link is for the Object constructor. Can someone please clarify what is being referred to here?

Thanks!
