### ISSUE TITLE
Internal Wiki Refactoring

### ISSUE THREAD

**Issue by bugron** [FreeCodeCamp/wiki#364]
Original issue: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6952

There are several issues with the current Wiki:

- [x] It is not possible to link to a specific page in the Wiki
- [ ] On the full-page version the address bar/url does not change when changing pages.
- [x] Images are not properly moved over.
- [x] Some internal links are not converted correctly

The current framework works like this:
The page is hosted on GH Pages and pulled in to the site via iframe for both the sidebar and into a full page iframe for the full page version.

### Proposed Refactor
1. Use nginx to proxy the page so it hangs off the /wiki url
2. Use an iframe to pull in a copy of the navbar - New endpoint on the main site
3. Implement a sidebar in react on the Wiki side to display the chat/map/wiki when clicked
4. Provide navbar -> react communication to toggle the sidebar displays
5. Only display the navbar in the full page version of the site.

**Comment by atjonathan** [comment]
The only issue that still needs addressed is: `On the full-page version the address bar/url does not change when changing pages`.

**Comment by Rafase282** [comment]
I'm closing this as we have migrated and the issues will not be the same.
