### ISSUE TITLE
Wiki solution Algorithm Symmetric Difference incomplete

### ISSUE THREAD

**Issue by otmeek** [FreeCodeCamp/wiki#370]
The wiki solution for algorithm symmetric difference is incomplete and doesn't pass all tests on its own.

Adding a loop that removes duplicate entries passes the tests. Like:

```
function sym() {

  var args = Array.prototype.slice.call(arguments);

  var getDifference = function(arr1, arr2) {
    function filterArr(arr1, arr2) {
      var a = arr1.filter(function(i) {
        return arr2.indexOf(i) === -1;
      });
      return a;
    }

    return filterArr(arr1, arr2).concat(filterArr(arr2, arr1));
  };

  var x = args.reduce(getDifference, []);

  // remove duplicates
  var newArr = [];
  for(var i = 0; i < x.length; i++) {
    if(newArr.indexOf(x[i]) === -1) {
      newArr.push(x[i]);
    }
  }

  return newArr;

}
```

Another user in the Javascript Help room noticed this as well. Please fix it!

**Comment by anuragaryan** [comment]
Can you please ignore the first two commit message, I messed up a little. 
https://github.com/anuragaryan/wiki/commit/10d0e788a00641786de1ba4e5ad64c11ff2c4a28 is the commit to be pulled.
