### ISSUE TITLE
Update certification articles

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/wiki#535]
We need to update all of our old certification articles and create new ones for our Back End and Data Visualization certifications.

Here are the current articles:

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Free-Code-Camp-Front-End-Development-Certificate
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Free-Code-Camp-Full-Stack-Development-Certificate

The new articles can follow the pattern shown in the Front End Development Certificate article. 

Not that these should be named "certification" (certificate is the actual piece of paper).

All the requirements for the certifications are listed in this challenge: http://www.freecodecamp.com/challenges/learn-how-free-code-camp-works

**Comment by varunu28** [comment]
Hi Quincy
Can I help with this one. If yes, then where to do the changes?

**Comment by raisedadead** [comment]
@varunu28 Yes sure! "Help Wanted" labels are open to all for contribution. Please go ahead. Remember to have a look at the [Contributing Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/CONTRIBUTING) if this is your first time.

**Comment by varunu28** [comment]
@raisedadead @QuincyLarson  I have updated certification details for Front end and full stack certification. I am working on creating new certificates for Backend and data visualization certificates.
