### ISSUE TITLE
Update Map to include all projects

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/wiki#538]
Here's our current map, which is out of date: https://github.com/FreeCodeCamp/wiki/blob/master/Map.md

We need to:
- [x] make sure the map itself has the challenges in the current sequence
- [x] add placeholder copy for challenges for which we don't yet have wiki articles
- [ ] add links to placeholder copy where we have since created articles

**Comment by Rafase282** [comment]
The only thing left is to add the real links when they get created.
