### ISSUE TITLE
Links given in the Home.md are not working

### ISSUE THREAD

**Issue by fakemonk1** [FreeCodeCamp/wiki#558]
I am a new member here and was looking for the "Guides on how to Contribute" in Home.md (The 
https://github.com/FreeCodeCamp/wiki/blob/master/Home.md), but the given links in the Home.md are not working/valid. I am not sure whether creating an issue for this is right, but I am creating this.

**Comment by tehkaiyu** [comment]
Seems like the last commit on that file changed all the absolute links to relative ones(https://github.com/FreeCodeCamp/wiki/commit/d072d15416ffbe1970deaf8ac871ec30da30b8b1), which is causing the issue you're seeing.

I wonder if there's a way to change the base url of the links instead of having all absolute urls

**Comment by raisedadead** [comment]
Hi @fakemonk1 @tehkaiyu ,

Refering a comment from @Rafase282 on #494 this is an expected side-effect.
> All links are now relative links and this should be the new standard for internal links. This might not work on the local wiki but it will work just fine on the live one.

The live wiki can be accessed here:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki

The "local" wiki is the Github repo for the actuall wiki.

**Comment by alayek** [comment]
But this would still have issues with @camperbot fetching data. Refer to https://github.com/FreeCodeCamp/camperbot/issues/64

**Comment by Rafase282** [comment]
We need to change camperbot internal to work with relative links instead of opening new PR for changing some from relative to hard links. All links were changed to relative so if they will be changed back it is best to do them all together.
