### ISSUE TITLE
Improve Translations Guide.

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/wiki#565]
The current version of the [Translations Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Translations-Guide) is bit technical for someone getting started as noted in the chat.

Points to be addressed:
- [x]  "remove the numbers, since these are essentially separate articles - not sequential steps." as noted [here](https://gitter.im/FreeCodeCamp/Translators?at=56e3b1b36fde057c268613fb).
- [x]  "Add GIF and Step by Step Instructions where applicable" as noted [here](https://gitter.im/FreeCodeCamp/Translators?at=56e3afa26fde057c268613b1).
- [ ] Clarify using Google Translator Kit, into a simpler workflow or explore alternate options such as [Transifex](https://www.transifex.com/customers/open-source/), as noted [here](https://gitter.im/FreeCodeCamp/Translators?at=56e34a0b9f24605773d76e3f).
- [x] Rewrite content to make it as simple as quoted [here](https://gitter.im/FreeCodeCamp/Translators?at=56e34a0b9f24605773d76e3f).

> found it too technical, many would give up before even trying
> it is all so confusing

- [x] Add list of currently active Translators Chat rooms as recommended by @vtamara 
- [ ] Add NOTES on migration from `nameXX` to `titleXX`

Please add anything else that is felt necessary to make the guide easier for everyone to follow, especially keeping in mind new contributors.

**Comment by SaintPeter** [comment]
The transition from using `nameXX` to `titleXX` will affect all ongoing translations.  I don't know precisely when we're going to roll out the change.  @BerkeleyTrue will need to tell us that.

What I can do is provide a node script to automatically convert a single file (or all of the files).  Please let me know what you prefer.

**Comment by raisedadead** [comment]
@SaintPeter Thanks a lot.

It would be great if you can come up with a script that can take individual files and update them with the change. (Considering there are some challenges that are partially translated, it would be easier to verify if at all longer). Thanking you again for making this extra effort :smile: !

Once the change `nameXX` to `titleXX` is actually merged. 

I'll update the guide on this, and let the involved Translators know for making the migration.

Additionally I'll also add a NOTE stating the new format is to be followed for the upcoming translations hence on.

Do you feel this would be the right path?

**Comment by SaintPeter** [comment]
I'm not sure when the actual transition is going to occur.  The script will simply ignore `titleXX` style, so it doesn't matter which you use.

**Comment by Rafase282** [comment]
@raisedadead what is the current status of this? I know it was not completed when it got merged but we need to know so we can finish it or close the issue.

**Comment by raisedadead** [comment]
@Rafase282 this has been taken up by @theflametrooper

**Comment by Rafase282** [comment]
Alright, thanks for the quick response.
