### ISSUE TITLE
Update How to get the MEAN stack running locally on OSX

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/wiki#568]
Refering a [comment on chat](https://gitter.im/FreeCodeCamp/HelpContributors?at=56e409177fefcd2a398c9f48)

The article [How to get the MEAN stack running locally on OSX](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-the-MEAN-stack-running-locally-on-OSX) needs to be updated.

**Comment by awesomeaniruddh** [comment]
I can work on this.

**Comment by raisedadead** [comment]
@awesomeaniruddh Thanks please go ahead! I'll give ya brownies :wink:
