### ISSUE TITLE
Ruby Strings

### ISSUE THREAD

**Issue by Nalipp** [FreeCodeCamp/wiki#576]
## Ruby Strings

Strings are a list of characters held between single or double quotes.

```'I am a string' "I am also a string"```

Character values held in a string are often assigned to variables.

```intro = 'I am a string'```

This enables us to store, retrieve and manipulate the values held within a string.

```username = 'DreadRobert'```  
```password = 'ilikerainbows'```  
```greeting = 'Welcome to our website'```  

## Strings containing quotes
Including quotes in a string will cause an error unless you follow these two exceptions.

**double quotes surrounding single quotes**  
```quote = "Salvador Dali once said, 'I don't do drugs. I am drugs.'"```

**single quotes with escaping**  
```quote = 'Salvador Dali once said, \'I don\'t do drugs. I am drugs.\''```

## String Interpolation #{}

String Interpolation allows us to insert ruby code into a string. A database of famous quotes could be managed like the following.

```author_name = "Mahatma Gandhi"```  
```quote = "Be the change you want to see in the world."```  

```shared_message = "#{author_name} once said, #{quote}"```

```puts shared_message```  
```Mahatma Gandhi once said, "Be the change you want to see in the world."```  

Or maybe a database of birthdays

```user_name = "Hayden"```  
```birthday = 1956```  
```age = 60```  

**Make you own message with the data**  
```shared_message = ```

## Exploring the documentation  
Manipulating stings is a core part of programing. Searching the documentation [(ruby-doc.org)](http://ruby-doc.org/core-2.2.0/String.html) is a fundamental skill. Some of the more common string manipulations in ruby include: _split, count, downcase, upcase, reverse, concat..._

**Comment by Nalipp** [comment]
Here is an intro to strings in Ruby. Not sure if this is the best way to submit the material, or if there is a better way to introduce the topic. But it's a brief intro.

**Comment by raisedadead** [comment]
@Nalipp Thanks for the write up. But we need this as a pull request. Please follow the [contributing guidelines here](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki#guides-on-how-to-contribute).

Secondly, you should have a look at #510 for currently needed articles and create content for them, including any which may not be on that list.

Should you need any assistance on contributing please visit our [dedicated wiki chat room](gitter.im/FreeCodeCamp/Wiki).

Closing this. But please do make a pull request as per the guideline mentioned.

Thanks!

**Comment by awesomeaniruddh** [comment]
Someone has already created an introduction to Ruby: https://github.com/FreeCodeCamp/wiki/pull/575

I suggest you wait for that PR to get merged, and add this to the file created in that PR.

**Comment by Nalipp** [comment]
Ok thank you. I will look at this again and get it done correctly.
