### ISSUE TITLE
Modify results list when searching for Java

### ISSUE THREAD

**Issue by sludge256** [FreeCodeCamp/wiki#577]
Currently, searches for "Java" related entries are buried under "JavaScript" entries.
Would it be a good idea to list "Java" entries at the top until the user appends an "s" to the search query?

**Comment by Rafase282** [comment]
I'm not sure how to implement that to be honest. Is this for the live wiki or https://github.com/FreeCodeCamp/FreeCodeCamp/wiki

**Comment by atjonathan** [comment]
This is fixed when you type:
`java` with a space after
on https://www.freecodecamp.com/wiki/en/. We don't need to worry about https://github.com/FreeCodeCamp/FreeCodeCamp/wiki yet, because we are retiring that soon.
