### ISSUE TITLE
Missing Images from How-to-start-when-you-are-stuck-(II)

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/wiki#588]
[How-to-start-when-you-are-stuck-(II)](https://github.com/FreeCodeCamp/freecodecamp/wiki/How-to-start-when-you-are-stuck-(II)) has missing images as noted in FreeCodeCamp/FreeCodeCamp#6935

@biancamihai appears to be the original author.

/cc @tasha-a-coder @bugron

**Comment by tasha-a-coder** [comment]
@biancamihai Have you and opportunity to check for the missing images?  If I can be of help in any way, let me know.

**Comment by biancamihai** [comment]
@tasha-a-coder please take the images from https://docs.google.com/document/d/1FA78Bt1Y-Rc5eDPHeYEDBJuxj1lWDOhw2oInP6ppZrE/edit?usp=sharing ;) let me know if you have any problems in viewing this document

**Comment by raisedadead** [comment]
@biancamihai Thanks a lot for helping out with the images.
