### ISSUE TITLE
Create Article: IDEs Editors Demystified

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/wiki#598]
<h3 align="center">Who Wins? Online vs Offline IDE</h3>

Write an article about online :airplane: IDEs and Editors, their advantages and disadvantages vs offline :rowboat: IDEs and Editors and their advantages and disadvantages.

<br>
<br>

> ----
<p align="center">Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Comment by abhisekp** [comment]
https://github.com/FreeCodeCamp/wiki/pull/664 adds a partial implementation of the required article.

If anyone wants to work on this, you may refer https://gist.github.com/Zirak/9999e97e01a7bd0a76f6 as a reference for offline editors.

**Comment by theflametrooper** [comment]
Closing as #651 addressed this issue.
