### ISSUE TITLE
Create Article: Laying out using Flexbox

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/wiki#606]
<h3 align="center">Flexbox Frenzy</h3>

Write an article about **Flexbox** layout. :newspaper:

<br>
<br>

> ----
<p align="center">Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Currently Assigned to:** @swheatley

> *If you want to work on this, please comment below and we can chat over* <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>gitter</b></a></kbd> 
Note: you may be assigned **only if** the current assignee doesn't respond withing the given timeframe.

**Comment by alayek** [comment]
If someone is willing to take this up; feel free to browser through following resources and consolidate the learning, after properly attributing them:

- [Flexbox Essentials](https://www.youtube.com/watch?v=G7EIAgfkhmg)
- [Flexbox Practical Examples](https://www.youtube.com/watch?v=H1lREysgdgc)
- [What The Flexbox?!](https://www.youtube.com/watch?v=Vj7NZ6FiQvo&list=PLu8EoSxDXHP7xj_y6NIAhy0wuCd4uVdid)
- [A Complete Guide to Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

**Comment by swheatley** [comment]
I'm interested in doing this.

**Comment by alayek** [comment]
@swheatley thanks for your interest! If you need help about anything, feel free to discuss in the [wiki chatroom](https://gitter.im/FreeCodeCamp/Wiki). Do you want me to assign it to you? Or would you like to work at your own pace?

**Comment by swheatley** [comment]
You can  assign it to me but I would also like to take it at my own pace :)

**Comment by alayek** [comment]
Sure @swheatley. Try to raise a PR within next week or so. If you are delayed for some reason, just let us know in the chatroom.

**Comment by swheatley** [comment]
I'm still planning on working on the flexbox wiki don't worry.  Just a little slow with getting started.

**Comment by abhisekp** [comment]
@swheatley More references

- :european_castle: :bomb: http://www.flexboxdefense.com/
- :frog: :four_leaf_clover: http://flexboxfroggy.com/
- :clock2: :five: http://flexboxin5.com/

**Comment by swheatley** [comment]
These are really cool.  I like flexboxfroggy

**Comment by theflametrooper** [comment]
Closing. This article was created in #728.
