### ISSUE TITLE
Create Article: Code Linting in JavaScript

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/wiki#608]
<h3 align="center">Catch Before it Crash</h3>

Write an article about **JavaScript code linting** and various popular linting tools available. :white_check_mark:

**Bonus :100: :** Write about other linters such as HTML, CSS, JSON, etc.
<br>
<br>

> ----
<p align="center">Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Comment by meetmangukiya** [comment]
Won't the linters be specific to the text editor?

**Comment by abhisekp** [comment]
@meetmangukiya linters are independent of text editor and are used for checking the source format and syntax.
