### ISSUE TITLE
Correct Algorithm Symmetric Difference Wiki Code Solution

### ISSUE THREAD

**Issue by daryl-c** [FreeCodeCamp/wiki#630]
Not sure if this is the correct way to bring up this issue, hopefully this is the right way.

Current code solution doesn't allow for filtering out multiples as is required by the solutions in the challenge. I have tweaked the current solution code to allow for this;

Original 

    function sym() {

    // Convert the argument object into a proper array
    var args = Array.prototype.slice.call(arguments);

    // Return the symmetric difference of 2 arrays
    var getDiff = function(arr1, arr2) {

    // Returns items in arr1 that don't exist in arr2
    function filterFunction(arr1, arr2) {
      return arr1.filter(function(item) {
        return arr2.indexOf(item) === -1;
      });
    }

    // Run filter function on each array against the other
    return filterFunction(arr1, arr2)
      .concat(filterFunction(arr2, arr1));
    };

    // Reduce all arguments getting the difference of them
    return args.reduce(getDiff, []);
    }

Changed version:

    function sym() {

      // Convert the argument object into a proper array
      var args = Array.prototype.slice.call(arguments);

      // Return the symmetric difference of 2 arrays
      var getDiff = function(arr1, arr2) {

    // Returns items in arr1 that don't exist in arr2
    function filterFunction(arr1, arr2) {
      return arr1.filter(function(item) {
        return arr2.indexOf(item) === -1;
      });
    }

    // Run filter function on each array against the other
    var finalArr = filterFunction(arr1, arr2)
      .concat(filterFunction(arr2, arr1));

    //Remove duplicates in filtered Arr
     return finalArr.filter(function(item, index){
      return finalArr.indexOf(item) === index;
    });

    };

    // Reduce all arguments getting the difference of them
    return args.reduce(getDiff, []);
    }

Can someone make this change so it fits with the challenge?

**Comment by alayek** [comment]
@daryl-c Are you taking about [this solution](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Algorithm-Symmetric-Difference#code-solution-1)?

Looks to me they are filtering through the array to remove duplicates at the end of that.

**Comment by daryl-c** [comment]
haha I could of sworn that wasn't there when I looked. Either way, its all good now!
