### ISSUE TITLE
Page permalink when?

### ISSUE THREAD

**Issue by indrakaw** [FreeCodeCamp/wiki#631]
It's nice to share wiki's page link to someone. Email it or share it over social medias. But currently, FreeCodeCamp Wiki doesn't support permalink(?) I have to copy github.io page URL link or blob link of the page. 

And if I copied, shared, and open the link via the site, it will redirect/open main page instead of page (e.g: https://www.freecodecamp.com/wiki/Why-You-Should-Try-Pair-Programming, will show https://www.freecodecamp.com/wiki/ ) And anchor text / link doesn't work well too.

Please fix.

**Comment by Rafase282** [comment]
Use this one instead when sharing wiki links, https://github.com/FreeCodeCamp/FreeCodeCamp/wiki

**Comment by abhisekp** [comment]
Or you may use the github.io link https://freecodecamp.github.io/wiki/en/Algorithm-Boo-who/ which points to the article directly.

**Comment by indrakaw** [comment]
:+1: @Rafase282 @abhisekp 
Thank you!
