### ISSUE TITLE
Create Articles: Twitch

### ISSUE THREAD

**Issue by theflametrooper** [FreeCodeCamp/wiki#701]
I can create all of these articles. However, if someone wants to help out, and has a good knowledge of twitch, leave a comment. The articles will include:

- [x] Explaining what Twitch is and setting up your Twitch Account
- [x] FreeCodeCamp on Twitch (Following FreeCodeCamp and getting alerts about when we go live)
- [x] Learn how to get started streaming yourself

If you have any more ideas for articles, please leave a comment!

**Comment by theflametrooper** [comment]
@Rafase282 https://github.com/FreeCodeCamp/wiki/blob/master/Twitch.md and https://github.com/FreeCodeCamp/wiki/blob/master/Stream-Your-Coding-Sessions-on-Twitch.tv.md can be deleted after these articles have been finished. The information is incorrect and outdated.

**Comment by Rafase282** [comment]
@theflametrooper I would say make a PR with their deletion after the new ones are merged. I think @Septimus created one about setting OBS or how to get started streaming, or was it only a medium post?

**Comment by theflametrooper** [comment]
@Rafase282 It was a Medium Post. I'll go more in depth probably.
