### ISSUE TITLE
Update Article: Add clauses to the Code of Conduct

### ISSUE THREAD

**Issue by sludge256** [FreeCodeCamp/wiki#731]
The article needs to mention trolling and spamming are not tolerated. As with the other clauses, such actions will incur appropriate action by an admin. There should also be a concise definition of the two.

For example:
>Trolling includes, but is not limited to these actions, ....

For reference:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Code-of-Conduct
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Gitter-Moderation-Policy

**Comment by SaintPeter** [comment]
>Spamming:  Repeatedly posting irrelevant, excessively large, and/or off-topic messages to a chat room

**Comment by abhisekp** [comment]
It also needs to be updated in the file associated with https://www.freecodecamp.com/code-of-conduct

**Comment by germainep** [comment]
I would like to tackle this issue if there is no one working on it.

**Comment by alayek** [comment]
Sure thing @germainep! If you need help with raising PR, contact us in the [Wiki chat](https://gitter.im/FreeCodeCamp/Wiki).

**Comment by Rafase282** [comment]
Looks good to me, waiting on some of the core team members to check on it.
