### ISSUE TITLE
I am sorry for the confusion and inconvenience.

### ISSUE THREAD

**Issue by WAKEUPMGPI** [FreeCodeCamp/wiki#740]
Earlier, I was setting up Git in a new editor and I have no idea why it posted nonsense on the repository? I should have made sure I was doing it properly. It worked but until I recieved a message I really did not know what it originally did. again, I am terribly sorry.

**Comment by Rafase282** [comment]
Could you point out where the changes that you made are?

**Comment by WAKEUPMGPI** [comment]
It was

**Comment by WAKEUPMGPI** [comment]
It is closed issue #8142.
