### ISSUE TITLE
Create Article: JavaScript Image Slider

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/wiki#768]
<h1 align="center">Sliding Images Easy</h1>

Write an article about creating **Image Slider using Pure JavaScript** :sunrise_over_mountains:

**Bonus :100: :** You may use jQuery

Ref.: https://coderwall.com/p/vsdrug/how-to-create-an-image-slider-with-javascript
<br>
<br>

> ----
<p align="center">Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Currently Assigned to:** @atjonathan

> *If you want to work on this, please comment below and we can chat over* <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>gitter</b></a></kbd>
Note: you may be assigned **only if** the current assignee doesn't respond within a given time-frame of 7 days.

**Comment by theflametrooper** [comment]
@abhisekp You say "using Pure JavaScript" and then underneath you say "You may use jQuery" :question:

**Comment by abhisekp** [comment]
@theflametrooper feel free to do it using jQuery :100: :+1:

**Comment by theflametrooper** [comment]
Reference: https://www.youtube.com/watch?v=KkzVFB3Ba_o
Code: http://codepen.io/theflametrooper/pen/BKMxxq
Things to add:

- [ ] HTML
- [ ] CSS
- [ ] JS
 - [ ] Variables
 - [ ] Animation
 - [ ] Pause and Play

I will only focus on the `javascript/jquery code` and just provide snippets to `html` and `css` as their not the focus.

**Comment by abhisekp** [comment]
@theflametrooper a tiny mini explanation about HTML structure would be nice :sparkles: coz that's what jQ depends on to make the slider possible. :100:
