### ISSUE TITLE
Bad solution code for the "Profile lookup" challenge

### ISSUE THREAD

**Issue by n00bax** [FreeCodeCamp/wiki#778]
link: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Checkpoint-Profile-Lookup#code-solution

The code solution in the profile lookup challenge wiki page is wrong(I think), I added the correct code below with an explanation inside comments in front of the modified line.
```js
for (var x = 0; x < contacts.length; x++){
    if (contacts[x].firstName === firstName) {
        if (contacts[x].hasOwnProperty(prop)) {  //instead of contacts[x][prop] because in that case it would return the value of that prop and if that prop was e.g 0  the if statement wouldn't work has expected.
            return contacts[x][prop];
        } else {
            return "No such property";
        }
    }
}
return "No such contact";

```

**Comment by koustuvsinha** [comment]
hey @n00bax ! good find. yes indeed using `hasOwnProperty` is a better solution. care to file a PR on [this file](https://github.com/FreeCodeCamp/wiki/blob/master/Checkpoint-Profile-Lookup.md)?
