### ISSUE TITLE
Create articles: Setting up Ubuntu for Programming

### ISSUE THREAD

**Issue by theflametrooper** [FreeCodeCamp/wiki#785]
1. Download and Install Ubuntu Desktop
2. Customising Ubuntu
3. Jazzing up the Terminal
4. Installing DevTools and modern web browsers
5. Downloading Text Editors and IDEs
6. Alternatives to popular Windows and Mac software

**Comment by Rafase282** [comment]
Well,

* install updates
* install filemanagers
* propietary drivers
* developper tools
* IDE
* setup rest of workspace (git, node, mongo or whatever you dev for)
* set aliases cause they are fun

That's what I did and normally do. So you want to set ubuntu from scratch meaning fresh installation or just for FCC web dev?

**Comment by theflametrooper** [comment]
@Rafase282 From scratch and for web dev (Not necessarily FCC)

**Comment by abhisekp** [comment]
- [ ] Download Latest and Greatest [**Ubuntu Desktop**](http://www.ubuntu.com/download/desktop)   
 _Also see [*alternative download methods*](http://www.ubuntu.com/download/alternative-downloads)_
- [ ] Updating/Upgrading Ubuntu to the latest software.
- [ ] Installing software using [Ubuntu's package managers](https://help.ubuntu.com/lts/serverguide/package-management.html) such as `apt` (_CLI_), `aptitude` (_CLI_), [**synaptic**](http://www.nongnu.org/synaptic/) (_GUI_) and [**Ubuntu Software Center**](https://apps.ubuntu.com/cat/applications/software-center/) (_GUI_)
- [ ] Adding [**ppa**](https://launchpad.net/ubuntu/+ppas) to get latest 3rd party software. 
- [ ] Install a Terminal Emulator such as [**Terminator**](https://launchpad.net/~gnome-terminator/+archive/ubuntu/ppa), shell replacements such as [**zsh**](http://www.zsh.org) and [**Oh My ZSH**](https://github.com/robbyrussell/oh-my-zsh).  
 _Also use plugins in ohmyzsh to speed up the productivity workflow._
- [ ] Searching for Ubuntu software PPAs and adding them before installing softwares.
- [ ] Example of building a software from source if prepackaged binary unavailable
- [ ] Install modern web browsers such as [**Chrome/Chromium**](http://www.ubuntuupdates.org/ppa/chromium_stable_channel)
- [ ] Installing [**Git**](https://launchpad.net/~git-core/+archive/ubuntu/ppa), [**NodeJS**](https://nodejs.org) via [**nvm**](https://github.com/creationix/nvm#install-script), [**Ruby**](https://www.ruby-lang.org/en/) via [**rvm**](https://rvm.io/rvm/install), and [**Python**](https://www.python.org/) via [**pyenv**](https://github.com/yyuu/pyenv#installation)
- [ ] Getting advanced with [**command**](http://cli.learncodethehardway.org/book/) [**line**](https://www.learnenough.com/command-line-tutorial)
- [ ] Install editors such as [**Atom**](url), [**Brackets**](url) or [**WebStorm**](url) for Web Development  
 _NOTE:- WebStorm is paid_

----
> **NOTE:-**
Links point to either their official page or installing instruction page
You may edit this comment and add any others and/or copy this to issue message (first comment) and use these suggestions

**Comment by theflametrooper** [comment]
@abhisekp Wow! Thanks so much. Let me take a look at the list, refine it and then i'll make it the issue description.
