### ISSUE TITLE
Splitting Articles 

### ISSUE THREAD

**Issue by theflametrooper** [FreeCodeCamp/wiki#797]
@alayek, @Rafase282 and @theflametrooper need to split all these articles into multiple ones which are smaller:

- [x] https://github.com/FreeCodeCamp/wiki/blob/master/Python-Basics.md
- [x] https://github.com/FreeCodeCamp/wiki/blob/master/Python-Functions.md **Waiting for Merge**
- [x] https://github.com/FreeCodeCamp/wiki/blob/master/Python-More-Builtin-Types.md **Waiting for Merge**
- [x] https://github.com/FreeCodeCamp/wiki/blob/master/Web-Development-in-Python.md **Waiting for Merge**
- [x] https://github.com/FreeCodeCamp/wiki/blob/master/Java-Loops.md **Waiting for Merge**
- [x] https://github.com/FreeCodeCamp/wiki/blob/master/Java-Basics.md **Waiting for Merge**

**Comment by Rafase282** [comment]
The Idea that I have is to split them by heading, and then have them link back to their parent.

**Comment by theflametrooper** [comment]
@Rafase282 Similar to this: https://github.com/FreeCodeCamp/wiki/blob/master/Python.md ?

**Comment by Rafase282** [comment]
I would say a [Back to -Parent Article Name-]() would be enough.

**Comment by Rafase282** [comment]
I'm going to take care of python basics.

**Comment by Rafase282** [comment]
I'll move to Python Functions now.

**Comment by Rafase282** [comment]
I'm working on Built-in types while the other gets reviwed/merged

**Comment by Rafase282** [comment]
@theflametrooper tag me on the next batch ;-)
