### ISSUE TITLE
Create Article: Writing a Node/NPM Module Easy

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/wiki#812]
<h1 align="center"><a href="https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328">Module Madness </a></h1>

Write an article about writing a basic **Node/NPM Module** :mushroom: 

**BONUS :100: :**  _Write detailed article splitting up in various pages_
<br>
<br>

> ----
<p align="center">Need Help? Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>or Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Currently Assigned to:** @jakegardner 

> *If you want to work on this, please comment below and we can chat over* <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>gitter</b></a></kbd>
Note: you may be assigned **only if** the current assignee doesn't respond within the given time-frame of 7 days.

**Comment by jakegardner** [comment]
I got this one.

**Comment by abhisekp** [comment]
@jakegardner Thank you for your interest :tada: 

I'm assigning this to you.
Please create an empty PR and write **`[in progress]`** in the PR title and push changes often :)

You may create an empty PR using 
```git
# Create a new branch from master
$ git checkout -b article/npm-module master

# Create an empty commit in the branch
$ git commit --allow-empty -m "Article: Create NPM Module" $

# push branch to remote
$ git push -u origin article/npm-module

# PR the branch to wiki `master` branch
```
