### ISSUE TITLE
[Vote Me] Navigation Button Proposal 

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/wiki#816]
Below are a list of proposals for navigating various related articles in the Wiki.

Please add your [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) to it.

Thanks :)

Everyone is welcome to vote :+1: :-1: :tada: :heart: 

----
cc: @FreeCodeCamp/wiki-mods

**Comment by abhisekp** [comment]
# Proposal 1 :ring: 

<div align="center">
<kbd><a href="Java-Intro">:point_left: <strong> Java Intro</strong><br>Previous</a></kbd> &mdash; <kbd align="center"><a href="java">:earth_asia: <strong>Java Home</strong> :earth_asia:<br>Table of Contents</a></kbd> &mdash; <kbd align="right"><a href="Java-Inheritance-Basics"><strong>Java Inheritance Basics</strong> :point_right:<br>Next</a></kbd>
</div>

**Comment by abhisekp** [comment]
# Proposal 2 :ring: 

<div align="center">
<a href="Java-Intro"><kbd>:point_left: <strong> Java Intro</strong><br>Previous</kbd></a> &mdash; <a href="java"><kbd align="center"> :earth_asia: <strong>Java Home</strong> :earth_asia: <br>Table of Contents</kbd></a> &mdash; <a href="Java-Inheritance-Basics"><kbd align="right"><strong>Java Inheritance Basics</strong> :point_right:<br>Next</kbd></a>
</div>

**Comment by abhisekp** [comment]
# Proposal 3 :ring: 

[**Previous**](Java-Intro) | [**Home**](Java) | [**Next**](Java-Inheritance-Basics)
:---|:---:|---:
<kbd><a href="Java-Intro"> :point_left: <strong>Java Intro</strong></a></kbd> | <kbd><a href="java"> :earth_asia: <strong>Java Home (TOC)</strong> :earth_asia: </a></kbd> | <kbd><a href="Java-Inheritance-Basics"><strong>Java Inheritance Basics :point_right: </strong></a></kbd>

**Comment by abhisekp** [comment]
# Proposal 4 :ring: 

[**Previous**](Java-Intro) | [**Home**](Java) | [**Next**](Java-Inheritance-Basics)
:---|:---:|---:
<a href="Java-Intro"><kbd> :point_left: <strong>Java Intro</strong></kbd> </a>| <a href="java"><kbd> :earth_asia: <strong>Java Home (TOC)</strong> :earth_asia: </kbd></a> | <a href="Java-Inheritance-Basics"><kbd><strong>Java Inheritance Basics :point_right: </strong></kbd></a>

**Comment by abhisekp** [comment]
# Proposal 5 :ring: 

<div align="center">
<a href="Java-Intro"><kbd>:point_left: <strong> Java Intro</strong></kbd></a> &mdash; <a href="java"><kbd align="center">:earth_asia: <strong>Java Home</strong> :earth_asia:</kbd></a> &mdash; <a href="Java-Inheritance-Basics"><kbd align="right"><strong>Java Inheritance Basics</strong> :point_right:</kbd></a>
</div>

**Comment by abhisekp** [comment]
# Proposal 6 :ring: 

<div align="center">
<kbd><a href="Java-Intro">:point_left: <strong> Java Intro</strong></a></kbd> &mdash; <kbd align="center"><a href="java">:earth_asia: <strong>Java Home</strong> :earth_asia:</a></kbd> &mdash; <kbd align="right"><a href="Java-Inheritance-Basics"><strong>Java Inheritance Basics</strong> :point_right:</a></kbd>
</div>

**Comment by Rafase282** [comment]
Should we just add one reaction per proposal, then use the party looking one for the winner? Also we could go for multiple options if you like more than one and then we narrow it down to 1.

**Comment by abhisekp** [comment]
@Rafase282 
these count as
- positive votes: :+1: :tada: :smile:  :heart: 
- negative votes: :-1: :confused:

**Comment by Rafase282** [comment]
I don't know why you put them all, that would render your vote null since you basically voted for all of them up and down.

**Comment by abhisekp** [comment]
@Rafase282 yeah! my votes will be the last vote. No issues :+1:

**Comment by abhisekp** [comment]
@Rafase282 @koustuvsinha @alayek check this out

----
<table align="center" width="100%">
  <tr>
    <td><a href="Java-Intro"> Java Intro </a></td>
    <td align="center"><a href="#java-basics"><kbd><kbd></kbd> <kbd></kbd> <kbd></kbd><br>
<b>Java Basics</b><br><kbd></kbd> <kbd></kbd> <kbd></kbd> <kbd></kbd> <kbd></kbd></kbd></a></td>
    <td align="right"><a href="Java-Inheritance-Basics">Java Inheritance Basics</a></td>
  </tr>
  <tr>
<td><a href="Java-Interface"> Java Interface </a></td>
<td align="center"><a href="Java-Classes"> Java Classes </a></td>
<td align="right"><a href="Java-Classes"> Java Classes </a></td>
</tr>
</table>

----
<div align="center" width="100%">
  <kbd><a href="#"> :point_left:<br><b>Prev</b></a></kbd> <b>|</b> <kbd align="center"><a href="#">:earth_asia:<br><b>Home</b></a>
  </kbd> <b>|</b> <kbd><a href="#"> :point_right:<br><b>Next</b></a></kbd>
</div>

**Comment by Rafase282** [comment]
I'm conflicted too, the top part with java basics.

**Comment by abhisekp** [comment]
@Rafase282 @theflametrooper the current article/topic is highlighted

**Comment by abhisekp** [comment]
@Rafase282 in the **Proposal 7**, it has an advantage that all articles are listed at the bottom of the article so that any one can go to any article or they may also be listed like this

<table align="center" width="100%">
  <tr>
    <td align="center"><a href="Java"> <b>&middot;&middot;&middot;</b> </a></td>
    <td align="center"><a href="#java-basics"><kbd><kbd></kbd> <kbd></kbd> <kbd></kbd><br>
<b>Java Basics</b><br><kbd></kbd> <kbd></kbd> <kbd></kbd> <kbd></kbd> <kbd></kbd></kbd></a></td>
    <td align="right"><a href="Java-Inheritance-Basics">Java Inheritance Basics</a></td>
  </tr>
  <tr>
<td><a href="Java-Interface"> Java Interface </a></td>
<td align="center"><a href="Java-Classes"> Java Classes </a></td>
<td align="center"><a href="Java"> <b>&middot;&middot;&middot;</b> </a></td>
</tr>
</table>

----
<div align="center" width="100%">
  <kbd><a href="#"> :point_left:<br><b>Prev</b></a></kbd> <b>|</b> <kbd align="center"><a href="#">:earth_asia:<br><b>Home</b></a>
  </kbd> <b>|</b> <kbd><a href="#"> :point_right:<br><b>Next</b></a></kbd>
</div>

**Comment by theflametrooper** [comment]
I think I prefer proposals 1 - 6. Not sure which ones though :laughing:

**Comment by SaintPeter** [comment]
I am not in love with the :earth_asia: Bookends :earth_asia: 
Having more than one looks weird to me.

I think I like the prev/home/next of Proposal 7 best, but I am not in love with the table of contents.  I really REALLY dislike this:
>   <td align="center"><a href="Java"> <b>&middot;&middot;&middot;</b> </a></td>
    <td align="center"><a href="Java-Basics">Java Basics</a></td>
    <td align="center"><a href="#java-inheritance-basics"><kbd><kbd></kbd> <kbd></kbd> <kbd></kbd><br>
<b>Java Inheritance Basics</b><br><kbd></kbd> <kbd></kbd> <kbd></kbd> <kbd></kbd> <kbd></kbd></kbd></a>

I loath those `<kbd><kbd>` marks.

**Comment by abhisekp** [comment]
# Proposal 8

<div align="left">
  <kbd><a href="Java-Intro">:point_left: <b>Java Intro</b></a></kbd>
</div>

<div align="center">
  <kbd><a href="Java-Basics"> :point_left:<br><b>Prev</b></a></kbd> <b>|</b> <kbd align="center"><a href="Java">:book:<br><b>Home</b></a></kbd> <b>|</b> <kbd><a href="Java-Inheritance-Basics"> :point_right:<br><b>Next</b></a></kbd><br>
</div>

<div align="right">
  <kbd><a href="Java-Interface-Basics"><b>Java Interface Basics</b> :point_right:</a></kbd>
</div>

----
@FreeCodeCamp/wiki-mods I think this is perfect. 
**See demo** :point_right: https://github.com/abhisekp/FreeCodeCamp-wiki/wiki/Wiki-Icons-and-Symbols

**Comment by Rafase282** [comment]
I'm confused with proposal 8. Prev and Next are the same or different from the other similar looking buttons?

**Comment by theflametrooper** [comment]
@abhisekp If you made it vertically aligned, then it would be awesome!

**Comment by abhisekp** [comment]
@Rafase282 they're same but it adds to the UI so that it shows the name of the next lesson. 
This is somewhat similar 

----
<div align="left">
  <a href="Java-Intro"><kbd>:point_left: <b>Java Intro</b></kbd></a>
</div>

<div align="center">
  <kbd><a href="Java-Basics">:arrow_backward:<br><b>Prev</b></a></kbd> <b>|</b> <kbd align="center"><a href="Java">:book:<br><b>TOC</b></a></kbd> <b>|</b> <kbd><a href="Java-Inheritance-Basics">:arrow_forward:<br><b>Next</b></a></kbd><br>
</div>

<div align="right">
  <a href="Java-Interface-Basics"><kbd><b>Java Interface Basics</b> :point_right:</kbd></a>
</div>

----

@theflametrooper they can't be made in a single line. But i think it looks OK this way.

**Comment by theflametrooper** [comment]
@abhisekp I just think it takes up too much space. It's definitely still my preferred proposal though.

**Comment by evaristoc** [comment]
7 is classic and that is why I prefer that one... Only that the prev and next should be at each side instead

**Comment by SaintPeter** [comment]
I really like the Book better than the worlds.  Also, the arrows are classy.

**Comment by Rafase282** [comment]
@abhisekp I just spoke with Quincy and we have to keep it as markdown.

**Comment by Rafase282** [comment]
This will be the new format, the only thing to change would be the icons if you want to propose different ones.

:point_left: [Prev]() | :book: [Home]() :book: |  [Next]() :point_right:  
:---|:---:|---:
 [**Java Basics**]() | [**Table of Contents**]() | [**Java Interface Basics**]() 

Icons by @abhisekp 
Table structure from [here](https://help.github.com/articles/organizing-information-with-tables/).

**Comment by QuincyLarson** [comment]
@Rafase282 LGTM. The only thing I would recommend is spelling out "Previous" instead (non-native English speakers may misunderstand what Prev means.

**Comment by theflametrooper** [comment]
Closing. We are using @Rafase282 's example: https://github.com/FreeCodeCamp/wiki/issues/816#issuecomment-216679394
