### ISSUE TITLE
Some links provided in the wiki do not work

### ISSUE THREAD

**Issue by carloselhalabi** [FreeCodeCamp/wiki#818]
There are 2 links in the [wiki](https://www.freecodecamp.com/wiki/en/) sending users to 404 pages (obviously, because they don't exist as they are specified).

1. The first 404 error is given when following the "How To Contribute From Your Browser" [link](https://freecodecamp.github.io/wiki/en/Guide-Online-Contribution).

2. The second 404 error is given when following the "Pull Request Guidelines" [link](https://freecodecamp.github.io/wiki/en/PULL_REQUEST_TEMPLATE).

![screenshot from 2016-04-28 22 51 09](https://cloud.githubusercontent.com/assets/2533088/14907647/ac0d188a-0d95-11e6-8356-6175438cc400.png)

**Comment by Rafase282** [comment]
@carloselhalabi the links and the whole page is outdated. We are trying to fix the script to update the page and sync it with the actual [wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki)

**Comment by carloselhalabi** [comment]
@Rafase282 Is somebody working on that? I'd like to check it out and help if I can

**Comment by alayek** [comment]
@carloselhalabi might want to join our [gitter chatroom](https://gitter.im/FreeCodeCamp/Wiki)

**Comment by Rafase282** [comment]
@carloselhalabi I'm working on getting the script working.

**Comment by Rafase282** [comment]
Seems like the links are pointing to freecodecamp.github.io as the base url instead of freecodecamp.com.

I'll take a look at it.
