### ISSUE TITLE
"Checkpoint" articles normalization

### ISSUE THREAD

**Issue by vcooley** [FreeCodeCamp/wiki#831]
It appears that checkpoints were removed and combined with challenges a while back. However, the articles corresponding to those are still prefixed with 'checkpoint-'. 

I'm working on a [ticket](https://github.com/FreeCodeCamp/wiki-generator/issues/12) on the main site and think that these should be changed to a 'challenge-' prefix as that's what they seem to be integrated into now. 

For instance:
[https://www.freecodecamp.com/wiki/en/**checkpoint**-convert-celsius-to-fahrenheit/](https://www.freecodecamp.com/wiki/en/checkpoint-convert-celsius-to-fahrenheit/)

should now be:
[https://www.freecodecamp.com/wiki/en/**challenge**-convert-celsius-to-fahrenheit/](
https://www.freecodecamp.com/wiki/en/challenge-convert-celsius-to-fahrenheit/)

If this is a beneficial change, I don't mind tackling it, but wondered what to do with the current pages prefixed with 'checkpoint-'. Can they be removed entirely or perhaps link to the page prefixed with 'challenge-' instead? Are dead links something to be worried about?

Edit: Formatting

**Comment by theflametrooper** [comment]
@vcooley Sounds good! If you want to submit a pr, go ahead! If not, I will jump on this!

**Comment by vcooley** [comment]
Cool, I'll do it!

**Comment by theflametrooper** [comment]
@vcooley I'll `QA` you :+1:

**Comment by Rafase282** [comment]
@vcooley keep in mind, that wiki is outdated. Like really old. Currently we need to get the generator up and runnign again so we can update the articles. This has already been corrected as far as I know.

We just need the wiki generator working again before we can work with the wiki you see on https://www.freecodecamp.com/wiki/en

**Comment by theflametrooper** [comment]
@Rafase282 @vcooley 
There are still a few that need changed:
![](https://i.gyazo.com/d195eeab5fc9494ef869caf2481fe934.png)

**Comment by Rafase282** [comment]
Alright, I'm checking with the core team about that, if we didn't change them it was for a reason, I just can't remember why.

**Comment by vcooley** [comment]
@Rafase282 
Thanks!

**Comment by vcooley** [comment]
I went ahead and submitted a PR, but its fine if it needs to be closed for whatever reason.
