### ISSUE TITLE
"Gitter" article should have link to our channels

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/wiki#843]
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Gitter
Self descriptive. Addition request.

#EasyContribution

**Comment by theflametrooper** [comment]
@hallaathrad Channels are available here: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Official-Free-Code-Camp-Chat-Rooms.

**Comment by hallaathrad** [comment]
Thanks @theflametrooper, I'm well aware of it.
Simply suggested the crosslinking to the list from the article. 

This should be a pretty simple PR and though either of us could do it, I want to leave it so others can make their first contribution.

Also, Don't we have an issue label for this sort of "easy-grab" sort of deal yet??

**Comment by theflametrooper** [comment]
@hallaathrad Awesome! I'll make a `easy` label!
