### ISSUE TITLE
Fix Repl.it integration copy and presentation

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/wiki#874]
![](https://www.evernote.com/l/Ar_wkSM6rgZKU4m8wIYW_aSUr4a6i7VNo7sB/image.png)

**Comment by abhisekp** [comment]
@QuincyLarson how about this one with **"Run code"** instead of "REPL it!"?

[![](http://i.imgur.com/oWwrA87.png)](http://i.imgur.com/oWwrA87.png)

in https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Algorithm-Diff-Two-Arrays#code-explanation
