### ISSUE TITLE
Normalize filenames and titles for the entire wiki

### ISSUE THREAD

**Issue by Rafase282** [FreeCodeCamp/wiki#889]
While working on https://github.com/FreeCodeCamp/wiki-generator/pull/26 I came to notice that we were using filenames to generate titles fr the live wiki. This is not the direction I want to follow, instead I tried to make the wiki generator look for titles in the form of `# Title here` or `#Title here` (Note, the second one while valid github markdown, is not the proper one, we should use the first one.) to have them become the title and by default use filenames if none were found.

Turns out that there were far too many with no titles, and far too many with titles such as `# Explanation:` because there was not proper title, these are mostly the algorithm challenges.

While on the wiki it might look fine since it displaus the filename as a title, the [live wiki](https://www.freecodecamp.com/wiki/en/) is what campers will be using the most and having double titles or filenames is a bad idea.

So we need to fix all articles to have valid and proper filenames according to our [guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/PULL_REQUEST_TEMPLATE).

So, by category we will be tackling them by Their Starting letter.

Letter | Assigned | Status
---- | ---- | ---- |
A |  @Rafase282 | #947 
B | @Rafase282 | #918
C |  @Rafase282 | #950
D | @Rafase282 | #917
E | @Rafase282 | #916
F |  @Rafase282 | #935
G | @Rafase282| #931 
H | @Rafase282 | #927 
I | @Rafase282 | #914
J | @Rafase282 | #924 
K | @Rafase282 | #913 
L | @Rafase282 | #912
M | @Rafase282 | #911 
N | @Rafase282 | #910
O | @Rafase282 | #909
P | @Rafase282 | #908 
Q | @Rafase282 | #903 
R | @Rafase282 | #902
S | @Rafase282 | #901
T | @Rafase282 | #895
U | @Rafase282 | #894 
V | @Rafase282 | #893 
W | @Rafase282 | #891 
X | N/A |
Y | N/A |
Z | N/A |
# | @Rafase282 | #892

**Comment by raisedadead** [comment]
This is a nice effort and a ton of hard work guys! You can assign me some (letter with least articles :wink: )

**Comment by Rafase282** [comment]
Feel free to pick them yourself and add your name to it. I'm going in order from Z to A. Just wanting to have my last PR merged before I work on others. The problem with this is that as we rename, some articles go to another letter so we have to be careful not to cause merge conflicts of any kind and to not leave _new_ filnes unchecked because they were rename after you finished with a section.

**Comment by hallaathrad** [comment]
Looks great to me (ready to merge from my end), except that some articles go like free-code-camp and some go freecodecamp... is that going to be addressed later? did I miss it?

**Comment by Rafase282** [comment]
Yes, that ones without a PR number are not ready yet. I haven't done the F section yet. I'll work on the rest today unless Jonathan has them ready.

**Comment by hallaathrad** [comment]
I'll wait until you've merged this before adding more cities then. Thanks for all the hard work, everyone! 💯

**Comment by Rafase282** [comment]
@hallaathrad I was hoping you would merge since it is related to campsites and I was the one to create the PR. I shouldn't merge my own.

**Comment by hallaathrad** [comment]
Hahaha i missed that bit. Thought you just wanted me to ok my part. It's done now, it seems.

**Comment by Rafase282** [comment]
Yeah, thanks though. I might be able to finish this today but now you can work on the campsites without conflicts with these changes.
