### ISSUE TITLE
Update the Typo Demo Wiki Article

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/wiki#922]
The below guide needs to be updated, because its creating confusion for new contributors.
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Contributions-Guide---with-Typo-Demo

it should be made up to date as per the latest:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md 

Refer
https://gitter.im/FreeCodeCamp/HelpContributors?at=5734c414e2996a5a42c7cfdd

**Comment by Rafase282** [comment]
We have been going over all out articles, we have yet to cover the ones starting with C. However, I think that article should be removed. I took a quicj glance at both and it seems to overlap, and the title itself in confusing.

See #889

**Comment by raisedadead** [comment]
@Rafase282 100% agreed. If others do not advise other wise this can go in favor of the main repo's CONTRIBUTING Guide.
