### ISSUE TITLE
Edit instruction to add issue number to commit message

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/wiki#923]
Near the bottom of the [Contributions Guide with Typo Demo](https://github.com/FreeCodeCamp/wiki/blob/master/Contributions-Guide---with-Typo-Demo.md), in [Step #7](https://github.com/FreeCodeCamp/wiki/blob/master/Contributions-Guide---with-Typo-Demo.md#step-7-creating-pull-request) we need to remove `closes #1337` from the sample commit message.

![image](https://cloud.githubusercontent.com/assets/2754821/15225060/6668ad8e-1831-11e6-8d0c-0f14de7b5bc7.png)

And we should remove the `=====` at the top as the leading `#` already makes it a header.

```
# Detailed Guide to Contributions.
===================================
```

**Comment by raisedadead** [comment]
@erictleung Refer #922 this might be taken down.

**Comment by erictleung** [comment]
@raisedadead ah I didn't see that you made that issue. I'll close this in favor of that one.
