### ISSUE TITLE
Asking for help, makes the bot angry

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/wiki#925]
Using the **`help`** or **`bot`** commands, the emoji in the markdown doesn't render properly due to the image markdown that follows it in the line.

See the screenshot below

> [![](http://i.imgur.com/Cwxwp9H.png)](http://i.imgur.com/Cwxwp9H.png)

**Solution:** Remove the emoji **`:speech_balloon:`** from the article

This is a markdown bug which `wontfix` so better to remove the emoji :speech_balloon: 

**File to be Modified:** [**camperbot.md** (wiki)](https://github.com/FreeCodeCamp/wiki/blob/master/camperbot.md)

<br>
<br>

> ----
<p align="center">Need Help? Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>or Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Currently Assigned to:** none

> *If you want to work on this, please comment below or we can chat over* <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>gitter</b></a></kbd>
Note: you may be assigned **only if** the current assignee doesn't respond within the given time-frame of 7 days.

**Comment by abhisekp** [comment]
The issue in https://github.com/FreeCodeCamp/wiki/issues/926 might also be fixed simultaneously with this one :smile:

**Comment by Rafase282** [comment]
If No one fixes this by the time I get to the C articles I'll fix it.
