### ISSUE TITLE
Symbol 2BAD doesn't render

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/wiki#926]
The symbol in http://unicode-table.com/en/2BAD/ doesn't render properly in many OSes by default such as Windows 10 and Mac OSX.

**Solution:-**
Replace that symbol from the following files

- [**camperbot.md** (wiki)](https://github.com/FreeCodeCamp/wiki/blob/master/camperbot.md)
- [**Help-Rooms.md** (wiki)](https://github.com/FreeCodeCamp/wiki/blob/master/Help-Rooms.md)

with the symbol in http://unicode-table.com/en/2191/
&nbsp;
<br>
<br>

> ----
<p align="center">Need Help? Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>or Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Currently Assigned to:** none

> *If you want to work on this, please comment below or we can chat over* <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>gitter</b></a></kbd>
Note: you may be assigned **only if** the current assignee doesn't respond within the given time-frame of 7 days.

**Comment by abhisekp** [comment]
The issue in https://github.com/FreeCodeCamp/wiki/issues/925 might also be fixed simultaneously with this one :smile:

**Comment by Rafase282** [comment]
If no one fixes this by the time I get to the H or C articles I'll fix it.
The H articles are next after https://github.com/FreeCodeCamp/wiki/pull/924 is merged.

**Comment by meetmangukiya** [comment]
Can I fix this?

**Comment by meetmangukiya** [comment]
Sorry for the previous comment , I was not able to fix this

**Comment by abhisekp** [comment]
@meetmangukiya no issues. May I know what was the issue while solving this?
&nbsp;
<br>
<br>

> ----
<p align="center">Need Help? Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>or Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Comment by meetmangukiya** [comment]
@abhisekp everything.. I don't know how you add such symbols in markdown and seriously I didn't search in Google either. I had like half an hour free.. Most of the time took me figuring out how to sync my fork :P . #925 was way too easy to even take a minute. In HTML it is just &blah; I'll have to see for markdown.. I think now am not a first timer and now this issue ain't for me :(

**Comment by akarshHegde** [comment]
Hey, i have sent a PR to fix page help-rooms.md . Could you review and provide feedback?
