### ISSUE TITLE
[Priority] Normalize all Algorithm Articles

### ISSUE THREAD

**Issue by Rafase282** [FreeCodeCamp/wiki#963]
Free Code Camp wants to make it so when you are on an algorithm challenge and the camper opens the live wiki from the page, it will directly point to the opened algorithm article for all supported spoken languages. 

Hence, to ensure that our valuable translators do not have to work twice, we need to start actively **implementing the new templates on all of the algorithm solution** articles as soon as possible.

**Comment by atjonathan** [comment]
Closing in favour of #1094
